apiVersion: v1
kind: Secret
metadata:
  name: <secret-name>
  namespace: <secret-ns>
type: Opaque
data:
  <secert-key>: <base64-encoded-password>
#OR
stringData:
  <secret-key>: "<password>"

# echo -n 'your-plain-password' | base64       #to encode password
# k apply -f <secret-file>

#kubectl create secret generic <secret-name> --from-literal=<secret-key>=<password> --from-literal=<secret-key-2>=<password2>... -n <secret-ns>

